import { tool } from '@langchain/core/tools';
import { z } from 'zod';

const MOCK_REQUIREMENTS: Record<
  string,
  {
    reqId: string;
    title: string;
    description: string;
    status: string;
    dependencies: string[];
    notes: string[];
  }
> = {
  'REQ-100': {
    reqId: 'REQ-100',
    title: 'Existing member profile enhancement',
    description: 'Add editable profile fields and sync user nickname across pages.',
    status: 'ready_for_analysis',
    dependencies: ['user-service'],
    notes: ['Existing profile page already supports avatar upload.'],
  },
  'REQ-200': {
    reqId: 'REQ-200',
    title: 'Authentication capability expansion',
    description: 'Introduce account login and single sign-on for enterprise users.',
    status: 'draft',
    dependencies: ['auth-service', 'sso-gateway'],
    notes: ['Current platform already has SMS verification in production.'],
  },
  'REQ-500': {
    reqId: 'REQ-500',
    title: 'Supplement login flow into current roadmap',
    description: 'Extend an existing requirement with login, session, and access control scope.',
    status: 'in_review',
    dependencies: ['auth-service', 'session-store'],
    notes: ['Need to verify overlap with current authentication roadmap.'],
  },
};

export interface ConflictCheckResult {
  hasConflict: boolean;
  reasons: string[];
}

export interface AnalysisToolOverrides {
  searchRequirement: (reqId: string) => Promise<unknown> | unknown;
  checkConflicts: (reqId: string, description: string) => Promise<ConflictCheckResult> | ConflictCheckResult;
}

export function createAnalysisTools(overrides: Partial<AnalysisToolOverrides> = {}) {
  const searchRequirement = overrides.searchRequirement ?? defaultSearchRequirement;
  const checkConflicts = overrides.checkConflicts ?? defaultCheckConflicts;

  return [
    tool(async ({ reqId }: { reqId: string }) => searchRequirement(reqId), {
      name: 'search_requirement',
      description: 'Look up an existing requirement by requirement id before doing further analysis.',
      schema: z.object({
        reqId: z.string().describe('Requirement id such as REQ-100 or REQ-20240315-001.'),
      }),
    }),
    tool(
      async ({ reqId, description }: { reqId: string; description: string }) => checkConflicts(reqId, description),
      {
        name: 'check_conflicts',
        description: 'Check whether the requirement conflicts with existing login or authentication capabilities.',
        schema: z.object({
          reqId: z.string().describe('Requirement id to check against existing scope.'),
          description: z.string().describe('Current requirement description or analysis target.'),
        }),
      },
    ),
  ];
}

export type AnalysisTools = ReturnType<typeof createAnalysisTools>;

async function defaultSearchRequirement(reqId: string) {
  return (
    MOCK_REQUIREMENTS[reqId] ?? {
      reqId,
      title: `Mock requirement for ${reqId}`,
      description: `No persisted detail found for ${reqId}. Treat this as a mock requirement lookup result.`,
      status: 'mocked',
      dependencies: [],
      notes: ['This entry is generated by the mock analysis tool.'],
    }
  );
}

async function defaultCheckConflicts(reqId: string, description: string): Promise<ConflictCheckResult> {
  const normalized = `${reqId} ${description}`.toLowerCase();
  const hasAuthConflict =
    /(登录|登入|认证|鉴权|密码|单点登录|sso|login|auth|authentication|password)/i.test(normalized);

  if (!hasAuthConflict) {
    return {
      hasConflict: false,
      reasons: ['No obvious overlap with the existing authentication scope.'],
    };
  }

  return {
    hasConflict: true,
    reasons: [
      'Authentication keywords overlap with an existing login roadmap.',
      'Please verify whether SSO, password login, and session handling already exist elsewhere.',
    ],
  };
}
